name: HotSpot
version: '1.4'
main: me.harpervenom.hotspot.HotSpot
api-version: '1.21'
depend:
  - packetevents
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE #
      required: false
    PacketEvents:
      load: BEFORE
      required: true
commands:
  lobby:
    description: "Перемещает в Лобби"
    usage: lobby
  spawn:
    description: "Перемещает в Лобби"
    usage: spawn